[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Set the Serial Monitor speed to match our code
monitor_speed = 115200

; Automatically download the required DHT22 libraries
lib_deps = 
	adafruit/DHT sensor library@^1.4.6
	adafruit/Adafruit Unified Sensor@^1.1.14