# Generated by Django 6.0.6 on 2026-06-16 17:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IoTNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(max_length=255, unique=True)),
                ('stall_location', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('battery_level', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=10)),
                ('batch', models.CharField(max_length=50)),
                ('vendor', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('statusBg', models.CharField(max_length=100)),
                ('qty', models.CharField(max_length=50)),
                ('days', models.CharField(max_length=50)),
                ('temp', models.CharField(max_length=50)),
                ('rh', models.CharField(max_length=50)),
                ('priceType', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('inquiries', models.CharField(max_length=100)),
                ('isAtRisk', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_id', models.CharField(max_length=50, unique=True)),
                ('buyerName', models.CharField(max_length=150)),
                ('buyerRole', models.CharField(max_length=100)),
                ('crop', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=50)),
                ('qty', models.CharField(max_length=50)),
                ('total', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('typeBg', models.CharField(max_length=100)),
                ('typeDot', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('statusBg', models.CharField(max_length=100)),
                ('statusDot', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CropBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=50, unique=True)),
                ('node', models.CharField(max_length=150)),
                ('icon', models.CharField(max_length=10)),
                ('crop', models.CharField(max_length=100)),
                ('scientific', models.CharField(max_length=150)),
                ('qty', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('arrival', models.CharField(max_length=100)),
                ('days', models.IntegerField(default=0)),
                ('daysColor', models.CharField(max_length=100)),
                ('temp', models.CharField(max_length=50)),
                ('rh', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('statusBg', models.CharField(max_length=100)),
                ('statusColor', models.CharField(blank=True, max_length=100, null=True)),
                ('iot_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.iotnode')),
            ],
        ),
        migrations.CreateModel(
            name='SensorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_c', models.DecimalField(decimal_places=2, max_digits=4)),
                ('humidity_rh', models.DecimalField(decimal_places=2, max_digits=4)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('crop_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_logs', to='api.cropbatch')),
                ('iot_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.iotnode')),
            ],
        ),
        migrations.CreateModel(
            name='WholesalerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stall_number', models.CharField(max_length=50)),
                ('market_location', models.CharField(default='Bulua WBIT Terminal', max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wholesaler_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='iotnode',
            name='wholesaler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='api.wholesalerprofile'),
        ),
        migrations.AddField(
            model_name='cropbatch',
            name='wholesaler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='api.wholesalerprofile'),
        ),
    ]
